version: '3.8'

services:
  app:
    build: .
    container_name: winter_cms
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: wintercms
      DB_USERNAME: root
      DB_PASSWORD: secret

  db:
    image: mysql:8.0
    container_name: winter_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: wintercms
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
